### ISSUE TITLE
mongoURI consistency

### ISSUE THREAD

**Issue by matthewroach** [OpenBD/openbd-core#1]
You can pass a mongoURI string into the `MongoRegister()` function via the argument mongouri, and you can also set session management to use a mongoDB at it's session store using a mongo string via `this.sessionmanagement`.

The two strings are a different format, could these be made to be the same format?

mongoRegister takes the following: `mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/database[?options]]`

this.sessionmanagement takes the following: `mongo://[user@pass:]server1:port1 server2:port2[/db]`

**Comment by a1anw2** [comment]
Oh good point, yes they should be the same format.

**Comment by a1anw2** [comment]
Looking through the code I now see why I coded it like this.  The problem is that the official MongoURI only supports having the /db/ if the user/pass is specified.   It ignores that property.  What i can do though is to do the parsing manually and support the official Mongo one.

So if we specify it as mongo:// then that is the "old" format, but if its given as "mongodb://" then that will be the new one.

http://api.mongodb.org/java/current/com/mongodb/MongoClientURI.html
